### PR TITLE
Retry upon 504 Gateway Timeout.

### PR DESCRIPTION
**Pull request by yunhailuo**
When I tried to post ~28K files, I came across 504 Gateway Timeout error every few thousand or even a few hundred files. It always happens at https://github.com/StanfordBioinformatics/encode_utils/blob/master/encode_utils/connection.py#L1376 . If I retry it, it's fine. I'm not exactly sure what happened. But I think it might be related to the fact that the file is just posted.

To fix it, I just let it retry 3 more times on 504 with some delays, using a function which is almost the same as here: https://www.peterbe.com/plog/best-practice-with-retries-with-requests .

### CODE REVIEW

**Comment by nate086** [comment]
Hi,

Sorry for the delay in getting back on this. It'll be easier for me to look this over when I'm back in two weeks.  For the meantime, if necessary you can update the timeout in line 75 of [__init__.py|https://github.com/StanfordBioinformatics/encode_utils/blob/master/encode_utils/__init__.py], which is currently set to 20 seconds.

**Comment by yunhailuo** [comment]
Please take your time. There is no rush for this. I changed timeout to 300 for other reason and it won't help with 504. The error is from the server side. Casey mentioned that they have tested that before and it seems that limiting request <200 per minute may help. Retry seems to work fine for me.

**Comment by p-sud** [comment]
@yunhailuo is this PR still useful? It sounds like an encoded fix would be more appropriate?

**Comment by yunhailuo** [comment]
Sure. Will close.

**Pull request closed without merging**
